### ISSUE TITLE
Kubernetes task on VSTS:"Error:spawn EACCES"

### ISSUE THREAD

**Issue by YadDish** [TsuyoshiUshio/KubernetesTask#21]
Hello,

I am trying to deploy docker image to kubernetes on VSTS for CD/CI pipeline. To start with I am testing for simple get command. I have given all the required details to fill the selection. Docker Container Registry Details, cluster details. and selected "get" command and passed "pods" as arguments. I end up getting this error.  "Error: spawn EACCES".

Thanking You in Advance!

![image](https://user-images.githubusercontent.com/29729002/27583454-b5986c54-5b34-11e7-8089-a4ebf12fb6d1.png)

**Comment by dtzar** [comment]
Are you using windows or linux build agent? Private or hosted?

**Comment by YadDish** [comment]
Linux build agent and hosted one

**Comment by TsuyoshiUshio** [comment]
Hi, This is the Microsoft official task. Not this repo. :)  Also I tried the task however, it didn't work well. If you like, you can use this task. You can search "kubernetes" via Marketplace. My task is authored by "Tsuyoshi Ushio"
