### ISSUE TITLE
Endpoint auth data not present while running the kubectl apply task

### ISSUE THREAD

**Issue by mmisztal1980** [TsuyoshiUshio/KubernetesTask#27]
While attempting to run `kubectl apply` from VSTS I'm getting the following:

```
413031Z ##[error]Endpoint auth data not present: 33b867a8-43f0-45ca-a41e-e5dd092fdbf2
2017-10-15T21:56:42.4443028Z ##[section]Finishing: [kubectl] apply (deployment)
```

Can you explain what does this error represent? I believe I've added the kubernetes service connection properly.

/Maciej

**Comment by dtzar** [comment]
What cloud provider are you trying to authenticate against K8s?  If it is GKE, they require an additional layer of authentication versus just kubeconfig (which is what this task is doing).

**Comment by mmisztal1980** [comment]
Can ypu point mento hendocumentation please?

Wysłane z iPhone'a

**Comment by dtzar** [comment]
Search for GKE here: https://github.com/dtzar/blog/tree/master/CD-Kubernetes-VSTS
