### ISSUE TITLE
Received Unhandled: First argument must be a string, Buffer, Arraybugger, Array or array-like object 

### ISSUE THREAD

**Issue by marcelbeeker** [TsuyoshiUshio/KubernetesTask#40]
I'll receive this error message when I use your task to deploy to a local Kubernetes clutster. Can you help me?

**Comment by esin** [comment]
Have same exception

I'm using Azure DevOps
```
2019-05-14T14:44:26.6429723Z Task         : Kubernetes Apply Task
2019-05-14T14:44:26.6429900Z Description  : Kubernetes Task. You can use kubectl apply by this command.
2019-05-14T14:44:26.6430033Z Version      : 3.0.3
2019-05-14T14:44:26.6430161Z Author       : Tsuyoshi Ushio
2019-05-14T14:44:26.6430372Z Help         : See [Kubernetes task](https://github.com/TsuyoshiUshio/KubernetesTask)
```

This error appears when I'm using in Kubernetes service connection "**Service account**", in other way (Kubeconfig) it works fine

Kubernetes in DigitalOcean

Thank you

**Comment by TsuyoshiUshio** [comment]
Hi guys, this task doesn't support Service account.  I develop this task before the official Kubernetes Task is created by the product team. However, they use the same name space as me. :( That is why Service Connection setting is took over by them. :( It is supported by official kubernetes task. 

I'm very happy to hear that you guys are using my task, however, the official task is already in use. :) Only reason that my task is useful is use istio on the pipeline. :)

**Comment by 4iter4life** [comment]
@TsuyoshiUshio which official Task should be used instead?
- task: kubectlgeneral@3 looks like a fork from your task :)
