### ISSUE TITLE
kubectl apply failed for version 0.1.31

### ISSUE THREAD

**Issue by TsuyoshiUshio** [TsuyoshiUshio/KubernetesTask#8]
I released version 0.1.31 however, it failed. Now I deploy 0.1.32 to revert the change. it works. 
However, 0.1.31 is added a feature for automated dowonload. I need to fix this problem.
Now I release this version instead. 

https://github.com/TsuyoshiUshio/KubernetesTask/tree/fix/cannotusedoubleminus

```
2017-03-20T13:55:28.9681690Z ##[section]Starting: kubectlapply 
2017-03-20T13:55:30.1279490Z ==============================================================================
2017-03-20T13:55:30.1534400Z Task         : Kubernetes Apply Task
2017-03-20T13:55:30.1815740Z Description  : Kubernetes Task. You can use kubectl apply by this command.
2017-03-20T13:55:30.2054020Z Version      : 0.1.31
2017-03-20T13:55:30.2310690Z Author       : Tsuyoshi Ushio
2017-03-20T13:55:30.2543460Z Help         : Kubernetes task
2017-03-20T13:55:30.2774970Z ===================================================================
    :
2017-03-20T13:55:33.2545400Z ##[error]Error: Not found configFile: ./kubeconfig
2017-03-20T13:55:33.3339500Z ##[section]Finishing: kubectlapply 

```
Simply this is because it can't find `.kubeconfig`

Only the difference of this line 

[works](https://github.com/TsuyoshiUshio/KubernetesTask/blob/fix/cannotusedoubleminus/kubectl.ts#L34)

[didn't work](https://github.com/TsuyoshiUshio/KubernetesTask/blob/master/kubectl.ts#L36)

**Comment by rakelkar** [comment]
Hmm - worked when I tested on a hosted linux agent... do you know why it didnt work for you? Are you possibly using a Windows agent?

**Comment by TsuyoshiUshio** [comment]
I tried on a hosted linux agent. I just update the task. Then I tried to create a release. The result was like that. One of the problem of the market place is we can't test in advance. :(  I also try to identify why it happens.

**Comment by rakelkar** [comment]
You can test by making the version 0.x.x and marking it as preview...
Customers should depend on 1.x.x versions...

**Comment by rakelkar** [comment]
Oh yeah... Download works for build scenario but fails for release... If
you can publish as 0.** and give me a repro of the issue I can connect with
the right guy in vsts support team...

Maybe we could release different build and release tasks to mitigate?

**Comment by rakelkar** [comment]
I added you to the thread... Sorry for the trouble... This aspect slipped
my mind in all the travel :(

**Comment by TsuyoshiUshio** [comment]
No problem. I appreciate your contribution. :) Let's tackle this problem together. 
Do I need to release current working version as 1.** then release 0.** as a preview?

**Comment by rakelkar** [comment]
Yes ... and you might want to add some user documentation indicating 1.x is
the stable one to use..

**Comment by TsuyoshiUshio** [comment]
I sorted out this problem. See the https://github.com/TsuyoshiUshio/KubernetesTask/pull/10 !
